name: Deploy to Kubernetes using Helm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t yourImageRepository:${{ github.sha }} .
        docker push yourImageRepository:${{ github.sha }}

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.23.0' 

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: Create kubeconfig file
      run: echo "${{ secrets.KUBECONFIG }}" > ${{ github.workspace }}/kubeconfig

    - name: Deploy to Kubernetes using Helm
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig
      run: |
       cd my-app       helm upgrade --install my-app . \
       --set image.repository=yourImageRepository \
       --set image.tag=${{ github.sha }} \
       --namespace my-app
